Messages Page
bcgov/traction pull request #318
Opened 2022-10-25 19:19 UTC by popkinj

- New Messages tab
![Screenshot from 2022-10-25 12-15-31](https://user-images.githubusercontent.com/479074/197862035-b1dab73c-8df0-427c-9eb7-17738e1af86d.png)
- New Messages page with table
![Screenshot from 2022-10-25 12-15-56](https://user-images.githubusercontent.com/479074/197862147-f7c499f9-3f20-4468-8f88-d0310f5df2b7.png)
- Custom API call
![Screenshot from 2022-10-25 12-16-34](https://user-images.githubusercontent.com/479074/197862454-94722bb3-5ff4-4b9b-bd20-3c6bcc4f81f8.png)

2022-10-25 19:52 UTC, loneil requested changes
Created and recieved message to/from bc wallet connection. But row expander is on the table but not doing anything

![image](https://user-images.githubusercontent.com/17445138/197868765-bab3155d-ba19-43c3-86eb-3befbcfea39c.png)

2022-10-25 19:52 UTC, loneil commented on services/tenant-ui/frontend/src/components/contacts/Contacts.vue
> +console.log('contact data', contacts);
Extra console log

2022-10-25 19:52 UTC, loneil commented on services/tenant-ui/frontend/src/store/index.ts
> +``;
Blank quote here

2022-10-25 19:52 UTC, loneil commented on services/tenant-ui/frontend/src/store/messageStore.ts
> +  //   });
Commented out code

2022-10-25 21:17 UTC, popkinj commented
> Created and recieved message to/from bc wallet connection. But row expander is on the table but not doing anything
> 
> ![image](https://user-images.githubusercontent.com/17445138/197868765-bab3155d-ba19-43c3-86eb-3befbcfea39c.png)

Was it supposed to do something?

2022-10-25 21:20 UTC, popkinj commented on services/tenant-ui/frontend/src/store/messageStore.ts
> +  //   });
Good catch.

2022-10-25 21:20 UTC, popkinj commented on services/tenant-ui/frontend/src/store/index.ts
> +``;
Got it.

2022-10-26 04:59 UTC, loneil commented
> > Created and recieved message to/from bc wallet connection. But row expander is on the table but not doing anything
> > ![image](https://user-images.githubusercontent.com/17445138/197868765-bab3155d-ba19-43c3-86eb-3befbcfea39c.png)
> 
> I think it's hooked up... there's just no content to show.

It's not hooked up, it's missing the row expansion slot and the RowExpandData component that shows the GET result of the message record.

2022-10-26 15:43 UTC, popkinj commented
> > > Created and recieved message to/from bc wallet connection. But row expander is on the table but not doing anything
> > > ![image](https://user-images.githubusercontent.com/17445138/197868765-bab3155d-ba19-43c3-86eb-3befbcfea39c.png)
> > 
> > 
> > I think it's hooked up... there's just no content to show.
> 
> It's not hooked up, it's missing the row expansion slot and the RowExpandData component that shows the GET result of the message record.

k... I'll have another look.

2022-10-27 16:58 UTC, popkinj commented
![Screenshot from 2022-10-27 09-57-35](https://user-images.githubusercontent.com/479074/198352678-b2b3ab71-9258-431b-ae34-34a58829c33d.png)
Think this is working now.

2022-10-27 18:09 UTC, loneil approved these changes
Working as expected. The Content table field doesn't make too much sense to have in there if Store Messages is off (the default) but we can look at that in a final UX later.

2022-10-27 18:36 UTC, merged