Add filters to table
bcgov/traction pull request #649
Opened 2023-06-06 17:09 UTC by Gavinok

Added filters to datatables as described in #478 as of now all filters are done via text input. Theoretically these filters could be changed to act as switches, a calendar view for dates etc. due to time constraints and the overhaul needed for that I think we should hold off until #452 is completed.

 Each filter is given a dedicated button to display as shown below
![image](https://github.com/bcgov/traction/assets/34443260/9b47de2d-f93c-4ec6-ae7f-c5c6db8b8aff)

When clicked a text input prompt is given where the user can filter the selected contents
![image](https://github.com/bcgov/traction/assets/34443260/66459c1e-760d-4cdb-b166-52863e26459b)

Alternatively there is a row view rather than the menu option. However, the menu option provides better support for future work adding new filter types as mentioned above.

2023-06-06 18:29 UTC, loneil commented on services/tenant-ui/frontend/src/store/utils/fetchList.ts
> +  list: Ref<T[]>,
Yes, thank you! Been meaning to add this at some point for better TS typing.

2023-06-06 19:57 UTC, loneil commented
Sample tenant for PR env

0ed8591b-a9d7-46ca-8bf0-d304ecc5f025
87114f99-80be-42ab-80f0-2091a95a96f7

2023-06-06 20:01 UTC, loneil requested changes
Don't seem to be able to click on other items than "Contains" in the filter popup

![image](https://github.com/bcgov/traction/assets/17445138/6c90fafd-b883-4617-b0ed-dd5d054b8497)

And trying spits some errors in the console (these from my local to see Vue warnings as well)

![image](https://github.com/bcgov/traction/assets/17445138/ee4fad67-88f3-4cc5-ab84-03b9fde3e9b2)


Probably ok to just have Contains without the other options if they can't work, but then we should hide the dropdown if that's available through the table settings, or if no other option use a global CSS to hide it.

2023-06-06 20:05 UTC, loneil commented
@Gavinok can we also add to the Innkeeper (reservations and history) tables as well? Thanks.
See https://pr-649-tenant-ui-dev.apps.silver.devops.gov.bc.ca/innkeeper (can find login credentials for lower environments in default.json if you don't know them already)

2023-06-06 21:33 UTC, Gavinok commented
@loneil I have removed the option to select the filtering mode and support for filtering in the innkeeper. Should resolve those requested changes

2023-06-06 21:57 UTC, loneil approved these changes
Looking good, should be fine with just the `contains` as the only option 👍

2023-06-07 21:02 UTC, loneil approved these changes

2023-06-07 21:03 UTC, merged